regions = SignalRegion SingleEleCR DoubleEleCR SingleMuCR DoubleMuCR

ROOT_FLAGS= -I$ROOTSYS/include -L$ROOTSYS/lib `root-config --cflags` `root-config --libs` -lFoam -lMathMore -Wno-deprecated

INCLUDE_SRC=-I$CMSSW_BASE/src/MonoZprimeJet/src/
